name = "peace-audio-worker"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
ELEVENLABS_API_KEY = "sk_df9cd2a55c76f283db024ba200b50cc374690d93bd8aaa92"
CLOUDINARY_CLOUD_NAME = "djb3falqu"
CLOUDINARY_API_KEY = "896336483661511"
CLOUDINARY_API_SECRET = "ZF0xTvvTZPNPzPDANflvpajBPW4"
