name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
